services:

  postgresql-db:
    image: postgres
    container_name: yuth-optician-postgresql
    restart: always
    ports:
      - 2345:5432
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    environment:
      POSTGRES_USER: ${ROOT_USERNAME}
      POSTGRES_PASSWORD: ${ROOT_PASSWORD}

  adminer:
    image: adminer
    container_name: yuth-optician-adminer
    restart: always
    ports:
      - 8081:8080
    depends_on:
      - postgresql-db
