services:

  yuth-optician-mongo-db:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${ROOT_PASSWORD}
    volumes:
      - /data:/data

  yuth-optician-mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${ROOT_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${ROOT_PASSWORD}
      ME_CONFIG_MONGODB_URL: mongodb://${ROOT_USERNAME}:${ROOT_PASSWORD}@0.0.0.0:27017/
      # ME_CONFIG_BASICAUTH: false
    depends_on:
      - yuth-optician-mongo-db
networks:
  default:
    name: yuthoptician_mongodb_network